config/routes.rb
Wifitocke::Application.routes.draw do  
  root :to => 'page#home'

  resources :categories
  resources :spots do
    collection do
      post :import
    end
    member do
      put :restore
      put :delete
      put :revert
    end
  end

  resources :cities
  resources :users do
    member do
      get :contact
      post :contact
    end
  end

  resources :user_sessions
  
  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/geolocate' => 'spots#geolocate', :as => :geolocate

  # What are these?
  match '/cities' => 'cities#index'
  match '/categories' => 'categories#index'
  match '/spots' => 'spots#index'
  match '/spots/:id' => 'spots#show', :id => :id
  match '/cities/:id' => 'cities#show', :id => :id
  match '/categories/:id' => 'categories#show', :id => :id  
end

app/models/spot.rb
# encoding: utf-8
class Spot < ActiveRecord::Base
  
  DEFAULT_LAT = 46.0620023
  DEFAULT_LNG = 14.5096064
  DEFAULT_ZOOM = 9
  
  # RESERVED_PERMALINKS = %w(spot spots city cities admin login logout signup)

  include SpotImporter
  
  acts_as_mappable :default_units => :kms,
                   :default_formula => :sphere  

  has_paper_trail
  
  has_friendly_id :title,
                  :use_slug => true,
                  :approximate_ascii => true #, :reserved_words => RESERVED_PERMALINKS 
  
  before_validation :geocode_address
  before_validation :set_defaults, :on => :create
  

  belongs_to :category
  belongs_to :user
  
  validates_presence_of :title
  validates_presence_of :category
  validates_presence_of :reason, :unless => Proc.new { |spot| spot.deleted == false }
  
  validates_uniqueness_of :permalink, :allow_blank => true
  
  scope :recent, :order => "created_at DESC", :limit => 10, :conditions => { :deleted => false }
  scope :deleted, :conditions => { :deleted => true }
  scope :active, :conditions => { :deleted => false }
  
  scope :invalid, :conditions => ["lat=? AND lng=? AND deleted=false", Spot::DEFAULT_LAT, Spot::DEFAULT_LNG]
  
  define_index do
    indexes title
    indexes location, city
    indexes ssid, key
    indexes notes
    
    has :open, :as => 'open' # should be written like this open is reserved by ruby

    # lat, lng should always be in radians not degrees
    has "RADIANS(lat)", :as => :latitude, :type => :float
    has "RADIANS(lng)", :as => :longitude, :type => :float

    # we don't index deleted spots
    where "deleted=false"
  end
  

  def set_defaults
    self.lat, self.lng = DEFAULT_LAT, DEFAULT_LNG if self.lat.blank? && self.lng.blank?
    self.zoom = DEFAULT_ZOOM if self.zoom.blank?
  end
  
  def validate
    errors.add_to_base "Prosimo, da določite kje se točka nahaja! Na zemljevidu (zgoraj) postavite marker na željeno lokacijo." if self.lat == Spot::DEFAULT_LAT && self.lng == Spot::DEFAULT_LNG
  end
  
  def latlng
    [self.lat, self.lng]
  end
  
  def full_location
    [location, city].join(" ").strip
  end
  
  def restore
    # skip_version do
    #   update_attributes({:deleted => false, :reason => nil})
    # end
  end
  
  def delete(reason)
    # skip_version do
    #   update_attributes({:deleted => true, :reason => reason})
    # end
  end
  
  def destroy!
    self.destroy
  end
  
  def permalink
    unless new_record?
      Rails.application.routes.url_helpers.spot_url self, :host => "wifi-tocke.si"
    end
  end
  
  def client_side_json
    options = {}
    options[:only] = [:id, :permalink, :title, :lat, :lng, :zoom, :description]
    # options[:methods] = [:unanswered_questions, :skips_left, :question_count, :textilized_instructions]
    to_json(options)
  end
  
  def has_notes?
    not (location.blank? && city.blank? && url.blank?)
  end
  
  

###########################
# PRIVATE
###########################
  
  private
  
    def geocode_address
      unless self.lat && self.lng
        geo = Geokit::Geocoders::MultiGeocoder.geocode(full_location)
        errors.add(:address, "Žal nismo uspeli najti podatkov o lokaciji na Google Maps. Preverite vnešene podatke.") if !geo.success
        self.lat, self.lng = geo.lat, geo.lng if geo.success
      end
    end
    
end

app/controllers/spots_controller.rb
# encoding: utf-8
class SpotsController < InheritedResources::Base
  
  # before_filter :require_user, :only => [:edit, :update, :destroy]
  # before_filter :authorize, :only => [:edit, :update, :destroy]
  before_filter :require_admin, :only => [:revert, :restore, :delete, :destroy]
  before_filter :ensure_friendly_url, :only => :show
  
  rescue_from 'Search::EmptyQuery' do
    redirect_to root_path
  end
  
  rescue_from 'Search::NoResults' do |e|
    # TODO Ce v bliznji okolici ni tock, potem ni nujno da je napacna geolokacija (primer: kotlje)
    unless e.geo_search
      flash[:notice] = "Ni rezultatov, ki ustrezajo iskalnemu kriteriju: <strong>#{e.query}</strong>.".html_safe
      redirect_to(root_path)
    else
      flash[:notice] = "<strong>Opozorilo:</strong> Niz <strong>#{e.query}</strong> smo poskusili geolocirati vendar iskanje ni vrnilo rezultatov. Poskušam še iskanje brez geolokacije.".html_safe
      flash.keep
      redirect_to(spots_path + "?q=#{e.query}&geo=false")
    end
  end
  
  rescue_from 'Search::NoGeoLocation' do |e|
    flash[:notice] = "Nismo uspeli dobiti podatkov o vnešeni lokaciji: <strong>#{e.address}</strong>."
  end
  
  def index
    @search = Search.new params
    @spots = @search.run # we don't want anyone to access index without search string
    
    respond_to do |format|
      format.html
      format.xml { render :xml => @spots }
    end
  end
  
  def new
    @spot = Spot.new :lat => Spot::DEFAULT_LAT, :lng => Spot::DEFAULT_LNG, :zoom => Spot::DEFAULT_ZOOM
  end
  
  def create
    @spot = Spot.new params[:spot]
    
    @spot.lat = params[:lat].blank? ? Spot::DEFAULT_LAT : params[:lat]
    @spot.lng = params[:lng].blank? ? Spot::DEFAULT_LNG : params[:lng]
    @spot.zoom = params[:zoom].blank? ? Spot::DEFAULT_ZOOM : params[:zoom]
    
    @spot.user = current_user if logged_in?
    
    if @spot.valid? && captcha_valid?
      flash.delete(:recaptcha_error) # why would we need a blank flash?
      @spot.save
      flash[:notice] = "WiFi točka je bila dodana! Hvala za pomoč!"
      redirect_to spot_url(@spot)
    else
      flash.delete(:recaptcha_error) # we don't need incorrect-captcha-sol as a message, do we?
      render :action => 'new'
    end
  end
  
  def edit
    @spot = Spot.find params[:id]
  end
  
  def update
    @spot = Spot.find params[:id]
    
    unless (params[:lat].empty? && params[:lng].empty? && params[:zoom].empty?)
      @spot.lat = params[:lat]
      @spot.lng = params[:lng]
      @spot.zoom = params[:zoom]
    end

    # @spot.updated_by = current_user || "Neznanec (#{request.remote_ip})"
    @spot.attributes = params[:spot]
    
    if @spot.valid? && captcha_valid?
      @spot.save
      flash.delete :recaptcha_error
      flash[:notice] = "Podatki za WiFi točko so bili posodobljeni."
      redirect_to spot_path(@spot)
    else
      flash.delete(:recaptcha_error) # we don't need incorrect-captcha-sol as a message, do we?
      render :action => 'edit'
    end
  end
  
  # Revert to an earlier spot version
  def revert
    # if params[:version]
    #   @spot = Spot.find params[:id]
    #   @spot.updated_by = current_user
    #   @spot.revert_to!(params[:version].to_i)
    #   flash[:notice] = "Verzija točke zamenjana."
    # else
    #   flash[:notice] = "Nepravilna verzija."
    # end
    flash[:error] = "Revert tock ni implementiran"
    redirect_to @spot
  end
  
  # Undelete spot
  def restore
    # @spot = Spot.find params[:id]
    # @spot.restore
    # flash[:notice] = "Točka ni več izbrisana."
    flash[:error] = "Restore tock ni implementiran"
    redirect_to @spot
  end
  
  def delete
    @spot = Spot.find params[:id]
    
    if captcha_valid?
      @spot.delete(params[:spot][:reason])
    
      if @spot.valid?
        flash[:notice] = "WiFi točka je bila odstranjena!"
        redirect_to spots_path
      else
        flash[:error] = "Za izbris moraš navesti razlog."
        redirect_to @spot
      end
    else
      flash[:error] = "reCaptcha ni bila pravilno prepisana!"
      redirect_to @spot
    end
  end
  
  def destroy
    @spot = Spot.find params[:id]
    @spot.destroy!
    flash[:notice] = "WiFi točka je bila odstranjena (tudi iz baze)!"
    redirect_to spots_path
  end  
  
  def import
    Spot.import_from_rss
    flash[:notice] = "Točke so bile importirane iz RSS vira!"
    redirect_to spots_path
  end
  
  def geolocate
    # http://localhost:3000/geolocate?lat=45.7977549812313&lng=15.1810706047881
    location = Geokit::Geocoders::MultiGeocoder.reverse_geocode( [params[:lat], params[:lng]] )
    
    render :text => location.full_address
    
    # respond_to do |format|
    #   format.html { location.full_address }
    #   format.js { render :text => location.full_address, :head => 200 }
    # end
    
  end

  
  private ########################################
  
    def authorize
      if current_user
        spot = Spot.find params[:id]
        unless spot.user_id == current_user.id || current_user.admin?
          store_location
          flash[:notice] = "Nimate pravic za ogled te strani!"
          redirect_to root_path
          return false
        end
      else
        store_location
        flash[:notice] = "Za ogled strani morate biti prijavljeni!"
        redirect_to login_path
        return false
      end
    end
    
    def require_admin
      if current_user
        unless current_user.admin?
          flash[:notice] = "Nimate pravic za ogled te strani!"
          redirect_to root_path
          return false
        end
      else
        store_location
        flash[:notice] = "Za ogled strani morate biti prijavljeni!"
        redirect_to login_path
        return false
      end
    end
   
    def collection
      @spots ||= end_of_association_chain.all.paginate :page => params[:page], :per_page => 20
    end
    
    def ensure_friendly_url
      # FIXME Loading @spot is unnecessary if we could call this method after inherited_resources does the magic :P
      #       We now probably have two Spot.find for show action
      @spot ||= Spot.find params[:id]
      redirect_to @spot, :status => :moved_permanently unless @spot.friendly_id_status.best?
    end
    
    def captcha_valid?
      return true if logged_in?
      verify_recaptcha(:model => @spot)
    end
  
end

app/helpers/spots_helper.rb
# encoding: utf-8
module SpotsHelper
  
  def spot_type(open)
    open ? "Odprto WiFi omrežje" : "Zaprto WiFi omrežje"
  end
  
end

app/views/spots/_form.html.haml
= render "shared/error_messages", :target => @spot

= hidden_field_tag 'lat', @spot.lat
= hidden_field_tag 'lng', @spot.lng
= hidden_field_tag 'zoom', @spot.zoom

#spot_details

  %dl      
    %dt= f.label :title, "Ime lokacije"
    %dd
      = f.text_field :title
      %span.hint Ime lokala, restavracije oz. objekta
    
    %dt Lokacija
    %dd
      %p Povlecite modro ikono na mesto kjer se nahaja WiFi točka na zemljevidu.
  
    %dt= f.label :category_id, "Kategorija"
    %dd
      = f.select :category_id, Category.all.collect {|c| [ c.name, c.id]}

    %dt= f.label :notes, "Opis"
    %dd
      = f.text_area :notes, :rows => 10, :cols => 40
      %span.hint
        Navedite ceno kave/piva, primernost prostora za sestanke, ...
        Za oblikovanje besedila lahko uporabljate
        = link_to "Textile", "http://textism.com/tools/textile/", :target => "_blank"

  %dl
    %dt= f.label :open, "Tip omrežja"
    %dd
      = f.select :open, [['Odprto',true], ['Zaščiteno', false]]
      %span.hint Je signal zaščiten z geslom ali je odprt?  

    %dt= f.label :ssid, "Signal (SSID)"
    %dd
      = f.text_field :ssid
      %span.hint Ime točke/signala
      
    %dt#pass_t
      = f.label :key, "Geslo za dostop"
    %dd#pass_d
      = f.text_field :key
      %span.hint Vpišite geslo, če ga veste
  
  - if @spot.new_record? || (logged_in? && current_user.admin?)
    %dl
      %dt= f.label :author, "E-mail / vzdevek"
      %dd
        = f.text_field :author
        %span.hint Ne skrbite, tudi mi ne maramo SPAMa. Vašega naslova ne bomo nikoli objavili.
  
  #notes
    %dl
      %dt= f.label :location, "Naslov"
      %dd
        = f.text_field :location
        %span.hint Vnesite čim bolj točen naslov. Primer: Dunajska cesta 100

      %dt= f.label :city, "Mesto, kraj"
      %dd
        = f.text_field :city
        %span.hint Primer: Ljubljana, Slovenj Gradec, Kranj
        
      %dt= f.label :url, "Spletna stran"
      %dd
        = f.text_field :url
        %span.hint Vpišite povezavo do spletne strani. Primer: http://wifi-tocke.si

  %p#toggle_notes
    = link_to_function 'Želim vnesti še dodaten opis', '$.hideNotes()'

    = recaptcha_tags
    
%br.clear

= javascript_tag do
  - unless @spot.has_notes?
    $('#notes').hide()
  - if @spot.open?
    $.togglePass()

app/views/spots/_geo_header.html.haml
-# %rdf:RDF{ "xmlns:rdf" => "http://www.w3.org/1999/02/22-rdf-syntax-ns#", "xmlns:geo" => "http://www.w3.org/2003/01/geo/wgs84_pos#" }
-#   %geo:Point
-#     %geo:lat= @item.lat    
-#     %geo:long= @item.lng

%meta{ :name => "geo.position", :content => @spot.latlng.join(";") }
-#%meta{ :name => "geo.placename", :content => "Liberty Island, New York, United States" }
-#%meta{ :name => "geo.region", :content => "us-ny" }

app/views/spots/_search.html.haml
= form_tag spots_path, :method => :get, :id => "search" do
  = hidden_field_tag :distance, 1
  = text_field_tag :q, @search.string
  
  %p#user_location
    %em pridobivamo vašo lokacijo ...
  /
    %label{:style => "display:block;"}
      = check_box_tag :geo, false, params[:geo], :style => "margin: 0; padding: 0; width: auto;"
      Iskanje brez geolokacije
    %br

  = submit_tag "Poišči točke", :class => "btn", :name => nil
  
:javascript
  $().ready(function() {
    $("#q").focus();
  });
  

app/views/spots/_spot.html.haml
= link_to h(spot.title), spot
%span
  - if spot.notes.blank?
    &nbsp;
  - else
    = truncate(spot.notes, :length => 100, :omission => '...')
- # TODO Spremeni CSS da bo podpiral 3 stolpce
- if false && spot.respond_to?(:distance)
  %span.distance
    = number_with_precision(spot.distance, 2)
    km

app/views/spots/_version.html.haml
- version = version.last.reify
%tr
  %td
    = version.number
  %td.changes
    - version.changes.each do |field, value|
      %p
        %span= field
        = value.join(' => ')
  %td
    - case version.user.class.to_s
    - when "User"
      = version.user.email
    - else
      = version.user
    
  %td
    - if version.number == @spot.version
      %span{:style=>'color:green;'} Trenutna različica
      = link_to "Prejšna različica", revert_spot_path(@spot) + "?version=#{version.number-1}", :method => :put
    - else
      = link_to "Nastavi za trenutno", revert_spot_path(@spot) + "?version=#{version.number}", :method => :put
    = link_to "Povrni v prvotno", revert_spot_path(@spot) + "?version=1", :method => :put

app/views/spots/edit.html.haml
- title "Uredi podatke"
- 
%h2 Uredi podatke

= form_for @spot do |f|
  = render :partial => "form", :locals => { :f => f }
  
  = submit_tag "Osveži"


:javascript
  $().ready(function() {
    wifi = new WifiMap()
    wifi.placeSpot(#{@spot.client_side_json})
    wifi.map.setCenter(wifi.spots[0].latlng)
    wifi.map.setZoom(#{@spot.zoom})
    wifi.makeEditable(wifi.spots[0])
  })

app/views/spots/index.html.haml
- title "Seznam brezplačnih WiFi točk"

= render :partial => "search"

.info
  = "Število najdenih točk: " + @spots.total_entries.to_s
  - if @search.location
    |
    = "Razdalja od iskane lokacije: " + @search.radius.to_s + " km"

- if @spots
  %ul#main_list
    = render @spots

  = will_paginate @spots
- else
  - # This teoreticaly never happens since Search raises exception that gets caught in spots_controller
  %p
    Nismo našli točk, ki bi ustrezali iskalnemu nizu
    %strong= @search.string

/ TODO Replace with jQuery alternative
%script{:type => "text/javascript"}
  $().ready(function() {
  wifi = new WifiMap()
  wifi.placeSpots([
  - @spots.each do |spot|
    = spot.client_side_json.html_safe + ","
  ], true)
  })

app/views/spots/new.html.haml
- title "Dodaj novo WiFi točko"

%h2 Vnesi novo WiFi točko

= form_for @spot do |f|

  - if false
    - if @user
      = hidden_field_tag :email, @user.email
    - else
      %dl
        %dt= label_tag :email, "E-mail"
        %dd
          = text_field_tag :email
          %span.hint
            V kolikor že imate račun,
            = link_to("se prijavite", login_path) + "."
      
  = render :partial => "form", :locals => { :f => f }

  = submit_tag "Dodaj točko"
  
%p
  = link_to "« Nazaj na seznam", spots_path
  
:javascript
  $().ready(function() {
    wifi = new WifiMap()
    wifi.placeSpot(#{@spot.client_side_json})
    wifi.makeEditable(wifi.spots[0])
    wifi.map.setCenter(wifi.spots[0].latlng)
  })

app/views/spots/show.html.haml
- title @spot.title
- keywords "#{@spot.title}, wifi točka, brezžično omrežje, brezplačna točka, brezplačen internet, dostop do interneta, wi-fi, wireless"
- description "Brezplačna WiFi točka: #{@spot.title} - #{@spot.notes}"

- content_for :head do
  = render :partial => "spots/geo_header"

%h2
  =h @spot.title
  = " (izbrisana)" if @spot.deleted?

%div.geo
  %span.latitude= @spot.lat
  %span.longitude= @spot.lng

%p
  = link_to_function 'Lociraj me', 'wu = new WifiUtil; wu.geolocate();'

%p
  = link_to "Uredi podatke", edit_spot_path(@spot), :rel => :nofollow
  - if logged_in? && (current_user == @spot.user || current_user.admin?)
    |
    - if @spot.deleted?
      = link_to "Restore", restore_spot_path(@spot), :method => :put
    - else
      = link_to_function "Izbriši", "$('delete').show()"
    |
    = link_to "Izbriši (iz baze)", spot_path(@spot), :method => :delete, :confirm => "Si prepričan da želiš popolnoma odstraniti točko? Undo ne obstaja!"

- if logged_in? && !@spot.deleted?
  #delete{:style => "display:none;"}
    - # Unfortunately forms only know :get and :post methods
    - form_for @spot, :url => delete_spot_path(@spot) do |form|
      = form.label :reason, "Razlog za izbris"
      %br
      = form.text_area :reason, :rows => 5
      %br
      = form.submit "Potrdi izbris"
      =# link_to "Potrdi izbris", delete_spot_path(@spot), :method => :delete, :confirm => "Si prepričan da želiš odstraniti točko?"

%dl
  %dt Kategorija
  %dd= @spot.category.name

  - unless @spot.location.blank?
    %dt Ulica ali naslov:
    %dd=h @spot.location
    
  - unless @spot.city.blank?
    %dt Kraj, Mesto:
    %dd=h @spot.city
      
%dl
  %dt Tip omrežja
  %dd
    = spot_type(@spot.open?)

  - unless @spot.ssid.blank?
    %dt SSID
    %dd=h @spot.ssid

  - unless @spot.open? || @spot.key.blank?
    %dt Geslo
    %dd=h @spot.key
  
%dl
  - unless @spot.url.blank?
    %dt Spletna stran
    %dd= link_to @spot.url, @spot.url, :target => '_blank', :rel => :nofollow
  
  - unless @spot.notes.blank?
    %dt Opis
    %dd
      = textilize(@spot.notes)

  - unless @spot.author.blank?
    %dt Avtor
    %dd=h @spot.author.split("@").first

%div.clear

- if logged_in? && current_user.admin?
  %dl
    %dt ID
    %dd= @spot.id
    
    %dt Permalink
    %dd= @spot.permalink

    - if @spot.deleted?
      %dt Razlog za izbris
      %dd= @spot.reason
  
  - # FIXME Versioning needs to be reimplemented
  - if false # @spot.versions.empty?
    %table#versions
      %thead
        %tr
          %th Verzija
          %th Spremembe
          %th Uporabnik
          %th &nbsp;
      %tbody
        - @spot.versions.each do |version|
          = # render :partial => 'version', :object => version
%p.clear
  = link_to "« Nazaj na seznam", spots_path


:javascript
  $().ready(function() {
    wifi = new WifiMap()
    wifi.placeSpot(#{@spot.client_side_json}, false)
    wifi.map.setCenter(wifi.spots[0].latlng)
  })