config/routes.rb
Wifitocke::Application.routes.draw do  
  root :to => 'page#home'

  resources :categories
  resources :spots do
    collection do
      post :import
    end
    member do
      put :restore
      put :delete
      put :revert
    end
  end

  resources :cities
  resources :users do
    member do
      get :contact
      post :contact
    end
  end

  resources :user_sessions
  
  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/geolocate' => 'spots#geolocate', :as => :geolocate

  # What are these?
  match '/cities' => 'cities#index'
  match '/categories' => 'categories#index'
  match '/spots' => 'spots#index'
  match '/spots/:id' => 'spots#show', :id => :id
  match '/cities/:id' => 'cities#show', :id => :id
  match '/categories/:id' => 'categories#show', :id => :id  
end

app/models/user.rb
# encoding: utf-8
# TODO Use Observer to deliver signup email

class User < ActiveRecord::Base
  
  acts_as_authentic do |c|
    # c.validate_login_field = false
    # c.validates_length_of_login_field_options = { :within => 2..5 }
  end
  
  has_many :spots, :dependent => :destroy
  
  def admin?
    %w(lenart.rudel@gmail.com nina.kozar@gmail.com blazek@gmail.com).include? self.email
  end
  
  def full_name
    return name unless name.blank?
    return email
  end
    
  def self.quick_create(email)
    pass = generate_password
    user = User.create(:email => email, :password => pass, :password_confirmation => pass)
    
    UserMailer.anonymous_signup_notification(user).deliver if user.valid?
    
    return user
  end
  

###########################
# PRIVATE
###########################
  
  private
    
    def self.generate_password
      # generate a random 8 digit password
      Authlogic::Random.friendly_token[0..7]
    end

end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  
  before_filter :require_user, :only => :index
  before_filter :authorize, :only => [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end
  
  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end
 
  def create
    @user = User.new(params[:user])
    
    if @user.save
      # OPTIMIZE Move this into an observer
      UserMailer.signup_notification(@user).deliver
      flash[:notice] = "Zahvaljujemo se vam za registracijo!"
      redirect_to @user
    else
      flash[:error]  = "Žal nismo uspeli ustvariti računa s temi podatki!"
      render :action => 'new'
    end
  end
  
  def edit
    @user = User.find params[:id] # allow admins to edit user (otherwise we could use current_user)
  end
  
  def update
    @user = User.find params[:id]
    
    if @user.update_attributes(params[:user])
      flash[:notice] = "Vaš profil je bil posodobljen."
      redirect_to user_path(@user)
    else
      render :action => 'edit'
    end
  end
  
  
  private ########################################
  
    def authorize
      if current_user
        # FIXME This doesn't work for index action (no user id in the params)
        user = User.find params[:id]
        unless user == current_user || current_user.admin?
          store_location
          flash[:notice] = "Nimate pravic za ogled te strani!"
          redirect_to root_path
          return false
        end
      else
        store_location
        flash[:notice] = "Za ogled strani morate biti prijavljeni!"
        redirect_to login_path
        return false
      end
    end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form.label :login
= form.text_field :login
= form.submit "Register"
=raw oauth_register_button :value => "Register with Twitter", :class => 'twitter'

app/views/users/_user_bar.html.haml
- if logged_in?
  = link_to "Moj profil (#{current_user.full_name})", current_user
  |
  = link_to "Odjava", logout_path
- else
  = link_to "Prijava", login_path
  |
  = link_to "Registracija", signup_path

app/views/users/edit.html.haml
%h2 My Account
%form.authentication_form{:action => connected_path, :method => :post}
  %fieldset
    %input{:type => :hidden, :name => :authentication_type, :value => :user}
    %input{:type => :hidden, :name => :_method, :value => :put}
    %legend Add another Oauth or OpenID provider.
    .oauth_providers
      %ul
        - %w(google facebook twitter).each do |name|
          %li.oauth_provider
            %img{:src => "/images/icons/#{name}.png"}
            %input{:type => :radio, :id => "#{name}_oauth_provider", :name => :oauth_provider, :value => name}
        .clearfix
  %fieldset
    %legend Or type in your OpenID address
    .openid_address
      %input.nice{:type => :text, :name => "openid_identifier"}
  %input.submit{:name => :submit, :type => :submit, :value => "Update"}/

app/views/users/new.html.haml
- title "Registracija uporabnika"

%h1 Registracija uporabnika

= error_messages_for :user
- if @user.errors.any? do
  %p
    - @user.errors.full_messages.each do |msg|
      = msg
      %br

= form_for @user do |f|

  = render :partial => 'form', :locals => { :f => f }

  %p= submit_tag 'Sign up'

app/views/users/show.html.haml
%h2= "Hi #{@profile[:name]}!"
- message = "You have connected to your"
- message << " #{current_user.authenticated_with.collect(&:titleize).join(" and ")}"
- message << " #{'account'.send(current_user.authenticated_with.length > 1 ? 'pluralize' : 'singularize')}."
%p= message
%img.profile{:src => @profile[:photo]}
%p
  %a{:href => @profile[:link]}= "Your on #{@profile[:title]}!"

- if local_request?
  =debug @profile