config/routes.rb
Wifitocke::Application.routes.draw do  
  root :to => 'page#home'

  resources :categories
  resources :spots do
    collection do
      post :import
    end
    member do
      put :restore
      put :delete
      put :revert
    end
  end

  resources :cities
  resources :users do
    member do
      get :contact
      post :contact
    end
  end

  resources :user_sessions
  
  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/geolocate' => 'spots#geolocate', :as => :geolocate

  # What are these?
  match '/cities' => 'cities#index'
  match '/categories' => 'categories#index'
  match '/spots' => 'spots#index'
  match '/spots/:id' => 'spots#show', :id => :id
  match '/cities/:id' => 'cities#show', :id => :id
  match '/categories/:id' => 'categories#show', :id => :id  
end

app/models/category.rb
# encoding: utf-8
class Category < ActiveRecord::Base
  
  has_many :spots, :dependent => :nullify
  
  validates_presence_of :name
  validates_presence_of :description

  validates_uniqueness_of :name, :case_sensitive => false
    
end

app/controllers/categories_controller.rb
# encoding: utf-8
class CategoriesController < InheritedResources::Base
  
  before_filter :authorize, :except => [:index, :show]
  
  def show
    show! do 
      @spots = @category.spots.paginate :per_page => 400, :page => params[:page]
    end
  end
  
  private ########################################
  
    def authorize
      unless current_user && current_user.admin?
        store_location
        flash[:notice] = "Nimate pravic za ogled te strani!"
        redirect_to root_path
        return false
      end
    end
    
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.haml
%li
  %h2= link_to h(category.name), category
  - if current_user && current_user.admin?
    = link_to "Uredi", edit_category_path(category)
    = link_to "Izbriši", category_path(category), :method => :delete, :confirm => "Si prepričan da želiš izbrisati kategorijo in vse pripadajoče točke?"
  %p= h(category.description)

app/views/categories/_form.html.haml
= error_messages_for :category

%p
  = f.label :name
  = f.text_field :name
  
%p
  = f.label :description
  %br/
  = f.text_area :description, :rows => 10, :cols => 40

app/views/categories/edit.html.haml
%h1 Uredi kategorijo

%p= link_to "Seznam kategorij", categories_path

- form_for @category do |f|
  = render :partial => "form", :locals => { :f => f }
  = submit_tag "Uredi kategorijo"

app/views/categories/index.html.haml
%h1 Seznam kategorij

- if current_user && current_user.admin?
  %p= link_to "Dodaj kategorijo", new_category_path

%ul
  - @categories.each do |category|
    = render :partial => category

app/views/categories/new.html.haml
%h1 Dodaj kategorijo

%p= link_to "Seznam kategorij", categories_path

- form_for @category do |f|
  = render :partial => "form", :locals => { :f => f }
  = submit_tag "Dodaj kategorijo"

app/views/categories/show.html.haml
%h1= @category.name

- if logged_in? and current_user.admin?
  %p
    = link_to "Uredi", edit_category_path(@category)
    = link_to "Izbriši", category_path(@category), :method => :delete, :confirm => "Si prepričan, da želiš izbrisati kategorijo in vse pripadajoče zapise?"

%p= @category.description

= @map.div(:width => 960, :height => 300)

%table
  = render @spots

= will_paginate @spots