config/routes.rb
Wifitocke::Application.routes.draw do  
  root :to => 'page#home'

  resources :categories
  resources :spots do
    collection do
      post :import
    end
    member do
      put :restore
      put :delete
      put :revert
    end
  end

  resources :cities
  resources :users do
    member do
      get :contact
      post :contact
    end
  end

  resources :user_sessions
  
  match '/signup' => 'users#new', :as => :signup
  match '/login' => 'user_sessions#new', :as => :login
  match '/logout' => 'user_sessions#destroy', :as => :logout
  match '/geolocate' => 'spots#geolocate', :as => :geolocate

  # What are these?
  match '/cities' => 'cities#index'
  match '/categories' => 'categories#index'
  match '/spots' => 'spots#index'
  match '/spots/:id' => 'spots#show', :id => :id
  match '/cities/:id' => 'cities#show', :id => :id
  match '/categories/:id' => 'categories#show', :id => :id  
end

app/views/layouts/_cities.html.haml
- form_tag cities_path, :method => :get do
  %fieldset
    %label
      Mesto:
      - active = @city.cached_slug if @city
      = select_tag 'city', options_for_select(City.all(:order => 'name asc').collect {|c| [c.name, c.cached_slug] }, active)
    /
      %label
        Kategorija:
        = select_tag 'category', options_for_select(Category.all.collect {|c| [c.name, c.id] })
    %noscript
      %div{:class => "noscript"}
        = submit_tag "Potrdi"
 
/ TODO Replace with jQuery alternative
:javascript
  document.observe("dom:loaded", function() {
    Event.observe($("city"), "change", function() {
      city = $("city");
      location.href = '#{cities_path}/' + city.getValue();
    });
  });

app/views/layouts/_facebook_like.html.haml
:plain
  <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwifi-tocke.si&amp;layout=standard&amp;show_faces=true&amp;width=450&amp;action=like&amp;font=tahoma&amp;colorscheme=light&amp;height=80" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:80px;" allowTransparency="true"></iframe>

app/views/layouts/_footer.html.haml
%div
  .copyright
    2010
    &copy;
    Vse pravice pridržane
    |
    = link_to image_tag("facebook.png", :alt => "Facebook", :style => "vertical-align: middle;"), "http://www.facebook.com/pages/WiFi-tocke/388201696064?ref=ts"
    |
    = mail_to("info@wifi-tocke.si", image_tag("email.png", :alt => "E-mail", :style => "vertical-align: middle"))
    |
    Sponzor gostovanja
    = link_to "Siel.si", 'http://www.siel.si', :title => 'Siel - Ruby gostovanje'
  
  .facebook
    - unless local_request?
      = render :partial => "/layouts/facebook_like"

app/views/layouts/_get_satisfaction.html.erb
<script type="text/javascript" charset="utf-8">
  var is_ssl = ("https:" == document.location.protocol);
  var asset_host = is_ssl ? "https://s3.amazonaws.com/getsatisfaction.com/" : "http://s3.amazonaws.com/getsatisfaction.com/";
  document.write(unescape("%3Cscript src='" + asset_host + "javascripts/feedback-v2.js' type='text/javascript'%3E%3C/script%3E"));
</script>

<script type="text/javascript" charset="utf-8">
  var feedback_widget_options = {};

  feedback_widget_options.display = "overlay";  
  feedback_widget_options.company = "wifitocke";
  feedback_widget_options.placement = "left";
  feedback_widget_options.color = "#222";
  feedback_widget_options.style = "idea";

  var feedback_widget = new GSFN.feedback_widget(feedback_widget_options);
</script>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-651180-14");
pageTracker._trackPageview();
} catch(err) {}</script>

app/views/layouts/application.haml
!!!
%html
  %head
    %title= yield(:title) || "WiFi točke"
    %meta{ "http-equiv" => "Content-Type", :content=> "text/html; charset=utf-8" }
    %meta{ :name => 'keywords', :content => yield(:keywords) || 'wifi točke, brezžična omrežja, brezplačne točke, brezplačen internet, dostop do interneta, wi-fi, wireless' }
    %meta{ :name => 'description', :content => yield(:description) || 'Seznam WiFi točk v Sloveniji, kjer lahko brezplačno dostopate do interneta. Poznaš tudi ti kako? Dodaj jo na zemljevid!' }
    
    /
      AUTHORS:
      Dusan Smolnikar, design | http://dusan.fora.si/
      Lenart Rudel, programming | http://twitter.com/lenartr
      Nina Kožar, Blaž Galič, idea & copy
    
    = stylesheet_link_tag "screen"
    = javascript_include_tag :defaults

    - if @spot
      = render :partial => "spots/geo_header"
    
    - if @map
      = GMap.header(:with_vml => false)
      =# javascript_include_tag("markerGroup")
      = javascript_include_tag("clusterer")
      = @map.to_html


  %body
  
    #head
      %h1= link_to(image_tag('wifi.gif', :alt => "Wifi") + image_tag('tocke.gif', :alt => "točke"), root_url)

      - form_tag cities_path, :method => :get do
        %fieldset
          %label
            Mesto:
            - active = @city.id if @city
            = select_tag 'city', options_for_select(City.all(:order => 'name asc').collect {|c| [c.name, c.id] }, active)
          /
            %label
              Kategorija:
              = select_tag 'category', options_for_select(Category.all.collect {|c| [c.name, c.id] })
          %noscript
            %div{:class => "noscript"}
              = submit_tag "Potrdi"

    - if false # TODO do we need this navigation?
      #user_navigation
        = render :partial => "users/user_bar"
        
      %ul#nav
        %li= link_to "Domov", root_path
        %li= link_to "Kategorije", categories_path
        %li= link_to "Mesta", cities_path
        %li= link_to "Seznam WiFi točk", spots_path
        %li= link_to "Dodaj WiFi točko", new_spot_path
        - if current_user && current_user.admin?
          %li= link_to "Uvozi RSS", import_spots_path, :method => :post, :confirm => "Si prepričan da želiš uvoziti nove točke?"

    - if @map
      #map
        = yield :map
      
    #controls
      = link_to '<span>Dodaj točko</span>', new_spot_path, :id => "add_point"
      
    #main
      - flash.each do |key, msg|
        = content_tag :div, msg, :class => "#{key} flash"

      = yield

    #footer
      %div
        2010
        &copy;
        Vse pravice pridržane
        |
        Komentarje in predloge sprejemamo na
        = mail_to("info@wifi-tocke.si", "info@wifi-tocke.si") + '!'
        |
        Sponzor gostovanja
        = link_to "Siel.si", 'http://www.siel.si', :title => 'Siel - Ruby gostovanje'
      
    - unless local_request?
      = render :partial => "layouts/google_analytics"
      =# render :partial => "layouts/get_satisfaction"

app/views/layouts/application.html.haml

!!!
%html
  %head
    %title= title_or_default
    %meta{ "http-equiv" => "Content-Type", :content=> "text/html; charset=utf-8" }
    
    %meta{ :name => 'keywords', :content => keywords_or_default }
    %meta{ :name => 'description', :content => description_or_default }
    %meta{ :name => 'author', :content => "Lenart Rudel s.p." }
    %meta{ :name => 'framework', :content => "Ruby on Rails" }

    /
      AUTHORS:
      Dusan Smolnikar, design | http://dusan.fora.si/
      Lenart Rudel s.p., programming | http://twitter.com/lenartr
      Nina Kožar, Blaž Galič, idea & copy

    
    = stylesheet_link_tag :screen
    = javascript_include_tag :application
    
    = '<script src="http://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>'.html_safe
    = yield :head

  %body.sub
    #wrapper
      #head
        %h1= link_to(image_tag('wifi.gif', :alt => "Wifi") + image_tag('tocke.gif', :alt => "točke"), root_url)

      - unless hide_map?
        #map_canvas
          = yield :map
      
        #controls
          = link_to '<span>Dodaj točko</span>'.html_safe, new_spot_path, :id => "add_point"
      
      #main
        - flash.each do |key, msg|
          = content_tag :div, msg.html_safe, :class => "#{key} flash"

        = yield

    #footer
      = render :partial => "/layouts/footer"

    - unless local_request?
      = render :partial => "layouts/google_analytics"
      = # render :partial => "layouts/get_satisfaction"

app/views/layouts/frontpage.html.haml
- @hide_map = true
!!!
%html
  %head
    %title= title_or_default
    %meta{ "http-equiv" => "Content-Type", :content=> "text/html; charset=utf-8" }

    %meta{ :name => 'keywords', :content => keywords_or_default }
    %meta{ :name => 'description', :content => description_or_default }
    %meta{ :name => 'author', :content => "Lenart Rudel s.p." }
    %meta{ :name => 'framework', :content => "Ruby on Rails" }

    /
      AUTHORS:
      Dusan Smolnikar, design | http://dusan.fora.si/
      Lenart Rudel s.p., programming | http://twitter.com/lenartr
      Nina Kožar, Blaž Galič, idea & copy
      
      This project is open-source.
      You are welcome to download the code and make improvements
      http://github.com/lenart/wifi-spots
    
    = stylesheet_link_tag :screen
    = javascript_include_tag :application
    
    = '<script src="http://maps.googleapis.com/maps/api/js?sensor=false" type="text/javascript"></script>'.html_safe
    = yield :head

  %body.front
    #wrapper
      #head
        #controls
          = link_to '<span>Dodaj točko</span>'.html_safe, new_spot_path, :id => "add_point"
    
      #main
        - flash.each do |key, msg|
          = content_tag :div, msg.html_safe, :class => "#{key} flash"

        %h1= link_to(image_tag('wifi.gif', :alt => "Wifi") + image_tag('tocke.gif', :alt => "točke"), root_url)

        = yield
      
    #footer
      = render :partial => "/layouts/footer"

    - unless local_request?
      = render :partial => "layouts/google_analytics"
      = # render :partial => "layouts/get_satisfaction"